
#ifndef HEAD_H
#define HEAD_H
#include <QApplication>
#include <QWidget>
#include <QLineEdit>
#include <QPushButton>
#include <QRegularExpression>
#include <QLabel>
#include <QChar>
#include <QDateEdit>
#include <QDate>
#include <QFile>
#include <QTextStream>
#include <QStandardItemModel>
#include <QListWidget>
#include <QAbstractItemView>
#include <QTimer>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QListWidget>
#include <QStringList>
#include <QHeaderView>
#include <algorithm>
#include <QComboBox>
#include <fstream>
#include <string>
#include <filesystem>

#include <QApplication>
#include <QMainWindow>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsRectItem>
#include <QGraphicsEllipseItem>
#include <QGraphicsPolygonItem>
#include <QVBoxLayout>
#include <QPushButton>
#include <iostream>
#include <QRandomGenerator>
#include <QStyleOptionGraphicsItem>
#include <QStyle>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QPainter>
#include <QStyleOptionGraphicsItem>
#include <QStyle>
#include <QStyledItemDelegate>
#include <set>
#include <QLineF>
#include <QPointF>
#include <QGraphicsLineItem>
#endif //HEAD_H
